### ISSUE TITLE
剩余步骤错误 + 提示略慢

### ISSUE THREAD

**Issue by MoienBowen** [alphaArgon/Minesweeper#2]
### 剩余步骤错误
同一局游戏，会有以下两种情况。在仍有一颗地雷的情况下，右上角剩余显示为 0，导致无法标记。
![Screenshot 2021-07-15 at 14.38.37.png](https://i.loli.net/2021/07/15/RHhmle3gouEAIvY.png)
![Screenshot 2021-07-15 at 14.39.38.png](https://i.loli.net/2021/07/15/DlaRNYKMd48hTjC.png)

### 另外 [#1](https://github.com/alphaArgon/Minesweeper/issues/1) 中提出, 点击 retry 仍然是相同分布，习惯上应该刷新。

**Comment by alphaArgon** [comment]
标记错误已知，感谢。
对于失败的提示，如果没有启用系统的减少动画，会有爆炸动画，再点击动画可以立即停止动画；如果启用了，会使用 0.5 s 淡出，考虑到要看清哪些地方有雷，会再过 0.5 s 来弹出 alert；将把后者的 0.5 s 取消

**Comment by n00d1e5** [comment]
❤️

**Comment by MoienBowen** [comment]
Close 完才想起来还有 comment……
alert 的 pop-up 可否改为可以移动？这样即使秒弹出，用户也可以通过移动 alert 从而看到地雷位置。

**Comment by alphaArgon** [comment]
> Close 完才想起来还有 comment……
> alert 的 pop-up 可否改为可以移动？这样即使秒弹出，用户也可以通过移动 alert 从而看到地雷位置。

感觉 macOS 一般只有无主的 alert 才会独立于窗口。（有比较不好的代替方法就是设定 Sad Mac 行为，来点一下才重新开始。）
